// TO DO: Wondering if makes more sense to combine some of these tests
@isTest
private class VillageTaskHandlerTest {

    @isTest
    static void cookDeliverMealTaskTest() {
        //For assignVillageTaskBeforeInsert()
    }

    @isTest
    static void buildFixTaskTest() {
        //For assignVillageTaskBeforeInsert()
    }

    @isTest
    static void healthAndSafetyCheckTaskTest() {
        //For assignVillageTaskBeforeInsert()
    }

    @isTest
    static void decorateTaskTest() {
        //For assignVillageTaskBeforeInsert()
    }

    @isTest
    static void gardenOutdoorTaskTest() {
        //For assignVillageTaskBeforeInsert()
    }

    @isTest
    static void otherTaskTest() {
        //For assignVillageTaskBeforeInsert()
    }

    @isTest
    static void emptyTaskListTest() {
        //For assignVillageTaskBeforeInsert()
    }

    @IsTest
    static void blockCriticalTaskDeleteTest() {
        //For stopCriticalTaskDelete()
    }

    @IsTest
    static void allowNormalTaskDeleteTest() {
        //For stopCriticalTaskDelete()
    }

    @IsTest
    static void nullTaskListTest() {
        //For stopCriticalTaskDelete()
        //Ideally refactor method or test Exception here
    }

    @IsTest
    static void bulkTaskDeleteTest() {
        //For stopCriticalTaskDelete()
    }

    @IsTest
    static void dueDateNullTest() {
        //For beforeBabyArrivesDeadlinesBeforeInsert()
    }

    @IsTest
    static void dueDateNotNullTest() {
        //For beforeBabyArrivesDeadlinesBeforeInsert()
    }

    @IsTest
    static void assignTaskBeforeCompletionTest() {
        //For requireAssignmentBeforeCompletion()
    }

    @IsTest
    static void alreadyAssignedTaskBeforeCompletionTest() {
        //For requireAssignmentBeforeCompletion()
    }

    @IsTest
    static void dmleExceptionTest() {
        //For requireAssignmentBeforeCompletion()
    }

    @IsTest
    static void otherExceptionTest() {
        //For requireAssignmentBeforeCompletion()
    }

    @IsTest
    static void bulkDeleteTest() {
        //For requireAssignmentBeforeCompletion()
    }

}