
@isTest
private class BabyMonitorRangeCalculatorTest {

    @isTest
    static void allRoomsInRange() {
        // TO DO: implement unit test
    }

    @IsTest
    static void someRoomsInRange() {

    }

    @IsTest
    static void noRoomsInRange() {

    }

    @IsTest
    static void negativeCoordinates() {
        
    }

    @IsTest
    static void monitorPositionListHasNulls() {

    }

    @IsTest
    static void rangeIsLessThanOrEqualToZero() {
        // Throws an exception
        // Fun exception message: 'Monitor broken, send back to manufacturer'
    }

    @IsTest
    static void roomsMapIsEmpty() {
        // Throws an exception
        // Fun exception message: You testing this monitor in a field or something?
    }

    @IsTest
    static void roomsMapHasNullValues() {
        // Throws an exception
        // Exception message: Did your house beome one-dimensional?    
    }
}