@isTest
private class BuildDecorSummaryTest {

    @isTest
    static void variousDecorations() {
        // TO DO: list with different decorations, some repeating
    }

    @isTest
    static void oneDecorationMultipleTimes() {
        // TO DO: list with same decoration multiple times
    }

    @isTest
    static void eachDecorationUnique() {
        // TO DO: List where each decoration is unique
    }

    @isTest
    static void emptyList() {
        // TO DO: empty list
    }

    @isTest
    static void emptyDecorationEntries() {
        // TO DO: For real-life example, handle when some entries are blank/null
    }

    @isTest
    static void caseSensitivity() {
        //TO DO: For real-life example, handle entries in uppercase, lowercase, mixed
    }

    @isTest
    static void ExceptionHandling() {
        //TO DO: Test for exception handling
    }
}