
@isTest
private class CalculateThreadNeededTest {

    @isTest
    static void nullNamesListTest() {
        // TO DO: assert return is 0
    }

    @IsTest
    static void emptyNamesListTest() {
        // TO DO: Assert return is 0
    }

    @IsTest
    static void positiveNamesListTest() {
        // TO DO: check letters List<String> matches expectations
        // TO DO: check neededThread returns expected result
    }

    @IsTest
    static void unexpectedLetter() {
        // TO DO: check exception thrown when letter not found in threadPerLetter Map
        // TO DO: If code refactored then check proper path followed
    }
}