
@isTest
private class MostNeededSupplyTest {

    @isTest
    static void eachItemUniqueTest() {
        // TO DO: implement unit test
    }

    @IsTest
    static void eachItemTheSameTest() {

    }

    @IsTest
    static void twoItemTie() {

    }

    @IsTest
    static void blankItemsInList() {

    }

    @IsTest
    static void nullItemsInList() {

    }

    @IsTest
    static void nullList() {
        
    }
}